# -*- coding: utf-8 -*-
"""AdCreative.ai_AI/ML_Implementation_Case_Study.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qy60sLaoIz0OtWQCb8_8M3fP29883T5J
"""

#!pip install rembg

#!pip install -U pillow

from rembg import remove
import requests
from PIL import Image
from io import BytesIO
import os

os.makedirs('original', exist_ok=True)
os.makedirs('masked', exist_ok=True)

img_url = "https://www.freepnglogos.com/uploads/perfume-png/perfume-png-transparent-images-png-only-12.png"
img_name = img_url.split('/')[-1]
img_name

img = Image.open(BytesIO(requests.get(img_url).content))
img.save('original/'+img_name,format='png')

output_path = 'masked/'+img_name
output_path

with open(output_path, 'wb') as f:
  input = open('original/'+img_name, 'rb').read()
  subject = remove(input, alpha_matting=True, alpha_matting_foreground_threshold=50)
  f.write(subject)

background_img = 'https://iso.500px.com/wp-content/uploads/2014/07/big-one.jpg'
background_img = Image.open(BytesIO(requests.get(background_img).content))

background_img = background_img.resize((img.width, img.height))

foreground_img = Image.open(output_path)
background_img.paste(foreground_img, (0,0), foreground_img)
background_img.save('masked/background.jpg', format='jpeg')