# -*- coding: utf-8 -*-
"""New_AdCreative.ai_AI/ML_Implementation_Case_Study.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qy60sLaoIz0OtWQCb8_8M3fP29883T5J
"""

#!pip install rembg

#!pip install -U pillow

from rembg import remove
import requests
from PIL import Image
from io import BytesIO
import os

os.makedirs('original', exist_ok=True)
os.makedirs('masked', exist_ok=True)

img_url = "https://www.freepnglogos.com/uploads/perfume-png/perfume-png-transparent-images-png-only-12.png"
img_name = img_url.split('/')[-1]
img_name

img = Image.open(BytesIO(requests.get(img_url).content))
img.save('original/'+img_name,format='png')

output_path = 'masked/'+img_name
output_path

with open(output_path, 'wb') as f:
  input = open('original/'+img_name, 'rb').read()
  subject = remove(input, alpha_matting=True, alpha_matting_foreground_threshold=50)
  f.write(subject)

background_img = 'https://thumbs.dreamstime.com/z/empty-top-white-marble-table-pink-wall-background-white-marble-table-pink-wall-background-121309056.jpg'
background_img = Image.open(BytesIO(requests.get(background_img).content))

background_img = background_img.resize((img.width, img.height))

foreground_img = Image.open(output_path)
background_img.paste(foreground_img, (0,0), foreground_img)
background_img.save('masked/background.jpg', format='jpeg')

background_img2 = 'https://i.pinimg.com/736x/52/83/5b/52835b86383d9194b985931735d7f643.jpg'
background_img2 = Image.open(BytesIO(requests.get(background_img2).content))

background_img2 = background_img2.resize((img.width, img.height))

foreground_img2 = Image.open(output_path)
background_img2.paste(foreground_img, (0,0), foreground_img)
background_img2.save('masked/background2.jpg', format='jpeg')

background_img3 = 'https://i.pinimg.com/originals/70/0c/7f/700c7f4ceaab20c0f440bb938be6b2b4.jpg'
background_img3 = Image.open(BytesIO(requests.get(background_img3).content))

background_img3 = background_img3.resize((img.width, img.height))

foreground_img3 = Image.open(output_path)
background_img3.paste(foreground_img, (0,0), foreground_img)
background_img3.save('masked/background3.jpg', format='jpeg')

background_img1 = 'https://img.freepik.com/free-photo/plain-pastel-orange-wall-with-white-marble-table-product_53876-96118.jpg?t=st=1686779563~exp=1686780163~hmac=ee9ee4fa8136b7111ff4dc9c57afbb1ac2c630e320af12467d9b09cb1640c738'
background_img1 = Image.open(BytesIO(requests.get(background_img1).content))

background_img1 = background_img1.resize((img.width, img.height))

foreground_img1 = Image.open(output_path)
background_img1.paste(foreground_img, (0,0), foreground_img)
background_img1.save('masked/background1.jpg', format='jpeg')